import type { SourceRecord } from "../../types";

export type AchhootSourceKey =
  | "ambedkar7"
  | "ambedkar1"
  | "ambedkar5"
  | "constitution"
  | "debates"
  | "pcr"
  | "census1931"
  | "olivelle"
  | "vivekanand"
  | "bayly"
  | "dirks"
  | "annotated"
  | "dnjha"
  | "rao";

type SourceTemplate = Omit<SourceRecord, "id"> & { key: AchhootSourceKey };

/**
 * A deliberately small, inspectable bibliography for the finished Hindi book.
 * Every URL is an official text, a university/library catalogue, or a scholarly
 * publisher page. Descriptions are bibliographic summaries, never invented
 * quotations or page references.
 */
export const ACHHOOT_SOURCE_TEMPLATES: SourceTemplate[] = [
  {
    key: "ambedkar7",
    title: "Dr. Babasaheb Ambedkar: Writings and Speeches, Volume 7 — The Untouchables",
    organization: "Dr. Ambedkar Foundation, Government of India",
    url: "https://www.mea.gov.in/images/CPV/Volume7.pdf",
    domain: "mea.gov.in",
    snippet: "Official collected-works edition containing The Untouchables: Who Were They and Why They Became Untouchables?",
    extractedText: "The official Volume 7 includes B. R. Ambedkar's The Untouchables. The work advances the Broken Men, Buddhism, beef-eating, and chronology arguments as Ambedkar's historical thesis. The text itself acknowledges missing links and the use of hypothesis; its propositions must therefore be distinguished from independently established facts.",
    publishedAt: "1948",
    retrievedAt: "2026-08-13",
    tier: 1,
    score: 100,
    used: true,
    language: "en",
    relevanceScore: 100,
    authorityScore: 100,
    primarySource: true,
    academicSource: false,
    reasonForInclusion: "आंबेडकर के मूल तर्क का आधिकारिक प्राथमिक पाठ।",
    author: "B. R. Ambedkar",
    year: "1948",
    publisher: "Dr. Ambedkar Foundation, Government of India",
    sourceType: "primary",
    identifier: "BAWS-7",
    relevantChapter: "1–11, 14",
    claimSupported: "आंबेडकर ने कौन-सा तर्क दिया; यह उस तर्क के सत्य होने का स्वतंत्र प्रमाण नहीं है।",
    verificationStatus: "verified",
    reliabilityNote: "Official collected works; primary source for Ambedkar's argument.",
    citation: "Ambedkar, B. R. The Untouchables: Who Were They and Why They Became Untouchables? (1948), in Dr. Babasaheb Ambedkar: Writings and Speeches, vol. 7. Government of India.",
  },
  {
    key: "ambedkar1",
    title: "Dr. Babasaheb Ambedkar: Writings and Speeches, Volume 1",
    organization: "Dr. Ambedkar Foundation, Government of India",
    url: "https://www.mea.gov.in/images/CPV/Volume1.pdf",
    domain: "mea.gov.in",
    snippet: "Official collected-works edition containing Castes in India and Annihilation of Caste.",
    extractedText: "Volume 1 contains Castes in India and Annihilation of Caste. These works explain Ambedkar's broader analysis of caste as enclosed, endogamous groups, a division of labourers, and a system of graded inequality that obstructs liberty, equality, fraternity, and associated life.",
    publishedAt: "1936",
    retrievedAt: "2026-08-13",
    tier: 1,
    score: 100,
    used: true,
    language: "en",
    relevanceScore: 98,
    authorityScore: 100,
    primarySource: true,
    academicSource: false,
    reasonForInclusion: "जाति पर आंबेडकर के व्यापक सामाजिक-राजनीतिक विश्लेषण का आधिकारिक पाठ।",
    author: "B. R. Ambedkar",
    year: "1916; 1936",
    publisher: "Dr. Ambedkar Foundation, Government of India",
    sourceType: "primary",
    identifier: "BAWS-1",
    relevantChapter: "2, 3, 4, 8, 11, 14",
    claimSupported: "जाति, अंतर्विवाह, श्रम-विभाजन और लोकतंत्र पर आंबेडकर के विचार।",
    verificationStatus: "verified",
    reliabilityNote: "Official collected works; primary source for Ambedkar's stated position.",
    citation: "Ambedkar, B. R. Castes in India; Annihilation of Caste, in Dr. Babasaheb Ambedkar: Writings and Speeches, vol. 1. Government of India.",
  },
  {
    key: "ambedkar5",
    title: "Dr. Babasaheb Ambedkar: Writings and Speeches, Volume 5 — Essays on Untouchables and Untouchability",
    organization: "Government of India",
    url: "https://www.mea.gov.in/images/CPV/Volume5.pdf",
    domain: "mea.gov.in",
    snippet: "Official collected essays on untouchables, social disabilities, lawlessness, labour, and village society.",
    extractedText: "Volume 5 collects Ambedkar's essays on the lived structure of untouchability: residential separation, civil disabilities, coerced or restricted labour, economic dependence, and the gap between formal citizenship and social power.",
    retrievedAt: "2026-08-13",
    tier: 1,
    score: 98,
    used: true,
    language: "en",
    relevanceScore: 97,
    authorityScore: 100,
    primarySource: true,
    academicSource: false,
    reasonForInclusion: "अस्पृश्यता के सामाजिक और आर्थिक रूपों पर आंबेडकर का प्राथमिक पाठ।",
    author: "B. R. Ambedkar",
    publisher: "Government of India",
    sourceType: "primary",
    identifier: "BAWS-5",
    relevantChapter: "2, 8, 12–14",
    claimSupported: "आंबेडकर द्वारा वर्णित सामाजिक, स्थानिक और आर्थिक बहिष्कार।",
    verificationStatus: "verified",
    reliabilityNote: "Primary source for Ambedkar's analysis, not neutral proof of every generalisation.",
    citation: "Ambedkar, B. R. Essays on Untouchables and Untouchability, in Dr. Babasaheb Ambedkar: Writings and Speeches, vol. 5. Government of India.",
  },
  {
    key: "constitution",
    title: "The Constitution of India — Article 17",
    organization: "Legislative Department, Ministry of Law and Justice, Government of India",
    url: "https://legislative.gov.in/constitution-of-india/",
    domain: "legislative.gov.in",
    snippet: "Official Constitution of India. Article 17 abolishes Untouchability and forbids its practice in any form.",
    extractedText: "Article 17 is in Part III of the Constitution. It abolishes Untouchability, forbids its practice in any form, and makes enforcement of any disability arising from it an offence punishable in accordance with law. This establishes legal abolition, not the ancient origin of the practice.",
    publishedAt: "1950-01-26",
    retrievedAt: "2026-08-13",
    tier: 1,
    score: 100,
    used: true,
    language: "en",
    relevanceScore: 100,
    authorityScore: 100,
    primarySource: true,
    academicSource: false,
    reasonForInclusion: "अस्पृश्यता के कानूनी उन्मूलन का सर्वोच्च प्राथमिक स्रोत।",
    author: "Constituent Assembly of India",
    year: "1950",
    publisher: "Government of India",
    sourceType: "legal",
    identifier: "Constitution-Article-17",
    relevantChapter: "2, 13, 14",
    claimSupported: "अनुच्छेद 17 का वास्तविक कानूनी पाठ और स्थिति।",
    verificationStatus: "verified",
    reliabilityNote: "Official constitutional text.",
    citation: "Constitution of India, art. 17. Legislative Department, Government of India.",
  },
  {
    key: "debates",
    title: "Constituent Assembly Debate on Draft Article 11 (Article 17), 29 November 1948",
    organization: "Constitution of India / Centre for Law and Policy Research",
    url: "https://www.constitutionofindia.net/debates/29-nov-1948/",
    domain: "constitutionofindia.net",
    snippet: "Digitised Constituent Assembly debate in which Draft Article 11 was considered and adopted.",
    extractedText: "The debate records support for abolishing caste-based untouchability, questions about leaving the term undefined, and warnings that legislation alone would not transform village practice. Draft Article 11 was adopted on 29 November 1948 and became Article 17.",
    publishedAt: "1948-11-29",
    retrievedAt: "2026-08-13",
    tier: 2,
    score: 97,
    used: true,
    language: "en",
    relevanceScore: 98,
    authorityScore: 94,
    primarySource: true,
    academicSource: true,
    reasonForInclusion: "संविधान सभा की बहस का खोजयोग्य अभिलेख।",
    author: "Constituent Assembly of India",
    year: "1948",
    publisher: "Centre for Law and Policy Research",
    sourceType: "archive",
    identifier: "CAD-1948-11-29",
    relevantChapter: "13–14",
    claimSupported: "प्रारूप अनुच्छेद की बहस, मतभेद और स्वीकृति।",
    verificationStatus: "verified",
    reliabilityNote: "Digitised archival transcript; use the debate as evidence of what members said.",
    citation: "Constituent Assembly of India. Debate on Draft Article 11, 29 November 1948. Constitution of India archive.",
  },
  {
    key: "pcr",
    title: "The Protection of Civil Rights Act, 1955",
    organization: "India Code, Government of India",
    url: "https://www.indiacode.nic.in/bitstream/123456789/15434/1/protection_of_civil_rights_act,_1955.pdf",
    domain: "indiacode.nic.in",
    snippet: "Official statute giving penal and administrative effect to Article 17.",
    extractedText: "The Act prescribes punishment for enforcing religious and social disabilities arising from untouchability, including denial of access to specified public places, institutions, goods, and services. It also assigns implementation duties to governments. It was originally enacted in 1955 and renamed through the 1976 amendment.",
    publishedAt: "1955-05-08",
    retrievedAt: "2026-08-13",
    tier: 1,
    score: 99,
    used: true,
    language: "en",
    relevanceScore: 99,
    authorityScore: 100,
    primarySource: true,
    academicSource: false,
    reasonForInclusion: "अनुच्छेद 17 को लागू करने वाला आधिकारिक अधिनियम।",
    author: "Parliament of India",
    year: "1955",
    publisher: "Government of India",
    sourceType: "legal",
    identifier: "Act-22-of-1955",
    relevantChapter: "13–14",
    claimSupported: "सिविल अधिकार संरक्षण अधिनियम की विषय-वस्तु।",
    verificationStatus: "verified",
    reliabilityNote: "Official statute database.",
    citation: "Protection of Civil Rights Act, 1955 (Act 22 of 1955). India Code, Government of India.",
  },
  {
    key: "census1931",
    title: "Census of India 1931, Volume I — India Report",
    organization: "Census of India / Digital Library of India",
    url: "https://archive.org/details/in.ernet.dli.2015.56018",
    domain: "archive.org",
    snippet: "Digitised 1931 census report associated with Census Commissioner J. H. Hutton.",
    extractedText: "The 1931 census is a primary source for colonial enumeration and administrative classification. Its caste and community categories record what officials counted and how they classified; they do not directly prove the identity or origin of communities in antiquity.",
    publishedAt: "1933",
    retrievedAt: "2026-08-13",
    tier: 2,
    score: 91,
    used: true,
    language: "en",
    relevanceScore: 92,
    authorityScore: 90,
    primarySource: true,
    academicSource: false,
    reasonForInclusion: "औपनिवेशिक जनगणना-वर्गीकरण का प्राथमिक दस्तावेज़।",
    author: "J. H. Hutton",
    year: "1933",
    publisher: "Manager of Publications, Government of India",
    sourceType: "archive",
    identifier: "Census-India-1931-Vol-1",
    relevantChapter: "9, 12",
    claimSupported: "औपनिवेशिक गणना और वर्गीकरण; प्राचीन उत्पत्ति नहीं।",
    verificationStatus: "verified",
    reliabilityNote: "Primary source for colonial administration; categories require critical reading.",
    citation: "Hutton, J. H. Census of India 1931, vol. I: India Report. Government of India, 1933.",
  },
  {
    key: "olivelle",
    title: "Dharmasūtras: The Law Codes of Āpastamba, Gautama, Baudhāyana, and Vasiṣṭha",
    organization: "University of California, Berkeley Law Library catalogue",
    url: "https://lawcat.berkeley.edu/record/412276?ln=en",
    domain: "berkeley.edu",
    snippet: "Library record for Patrick Olivelle's scholarly translation and edition of the Dharmasūtras.",
    extractedText: "Patrick Olivelle's translation presents the four surviving early Brahmanical expert texts on dharma with philological introduction and notes. Such normative texts show prescriptions and classifications advanced by learned authors; they cannot by themselves be treated as a census of uniform everyday practice.",
    publishedAt: "2009",
    retrievedAt: "2026-08-13",
    tier: 3,
    score: 92,
    used: true,
    language: "en",
    relevanceScore: 93,
    authorityScore: 95,
    primarySource: false,
    academicSource: true,
    reasonForInclusion: "धर्मसूत्रों के आलोचनात्मक अनुवाद का विश्वविद्यालय पुस्तकालय अभिलेख।",
    author: "Patrick Olivelle (translator and editor)",
    year: "2009",
    publisher: "Oxford University Press",
    sourceType: "scholarly",
    identifier: "ISBN-9780199555376",
    relevantChapter: "4, 5, 6, 9–11",
    claimSupported: "धर्मसूत्रों की प्रकृति और उपलब्ध आलोचनात्मक संस्करण।",
    verificationStatus: "verified",
    reliabilityNote: "Scholarly edition; normative source must not be equated automatically with social practice.",
    citation: "Olivelle, Patrick, trans. and ed. Dharmasūtras: The Law Codes of Ancient India. Oxford University Press, 2009.",
  },
  {
    key: "vivekanand",
    title: "Candāla: Untouchability and Caste in Early India",
    organization: "Primus Books",
    url: "https://primusbooks.com/candalas/",
    domain: "primusbooks.com",
    snippet: "Scholarly collection by historian Vivekanand Jha on Candalas, Nisadas, and stages in early untouchability.",
    extractedText: "Vivekanand Jha traces a long, staged development in which groups such as Candalas and Nisadas were increasingly excluded and degraded. This model differs from Ambedkar's specific Broken Men, Buddhist, and beef-eating causal chain and stresses gradual social stratification.",
    publishedAt: "2017",
    retrievedAt: "2026-08-13",
    tier: 3,
    score: 91,
    used: true,
    language: "en",
    relevanceScore: 96,
    authorityScore: 92,
    primarySource: false,
    academicSource: true,
    reasonForInclusion: "अस्पृश्यता के आरंभिक इतिहास पर वैकल्पिक विद्वत् व्याख्या।",
    author: "Vivekanand Jha",
    year: "2017",
    publisher: "Primus Books",
    sourceType: "scholarly",
    identifier: "ISBN-9789386552556",
    relevantChapter: "4, 9–11",
    claimSupported: "क्रमिक विकास और चांडाल/निषाद संबंधी वैकल्पिक इतिहास-लेखन।",
    verificationStatus: "verified",
    reliabilityNote: "Scholarly secondary work; one interpretation in a disputed field.",
    citation: "Jha, Vivekanand. Candāla: Untouchability and Caste in Early India. Primus Books, 2017.",
  },
  {
    key: "bayly",
    title: "Caste, Society and Politics in India from the Eighteenth Century to the Modern Age",
    organization: "Cambridge University Press",
    url: "https://doi.org/10.1017/CHOL9780521264341",
    domain: "doi.org",
    snippet: "Susan Bayly's historical and anthropological study of caste across precolonial, colonial, and modern change.",
    extractedText: "Susan Bayly treats caste formations as historically variable and contingent rather than as one unchanged essence. Her analysis emphasises political economy, regional difference, state formation, colonial rule, and modern politics.",
    publishedAt: "1999",
    retrievedAt: "2026-08-13",
    tier: 3,
    score: 93,
    used: true,
    language: "en",
    relevanceScore: 94,
    authorityScore: 96,
    primarySource: false,
    academicSource: true,
    reasonForInclusion: "जाति की ऐतिहासिक परिवर्तनशीलता पर मानक विद्वत् अध्ययन।",
    author: "Susan Bayly",
    year: "1999",
    publisher: "Cambridge University Press",
    sourceType: "scholarly",
    identifier: "DOI-10.1017/CHOL9780521264341",
    relevantChapter: "8, 10, 12, 14",
    claimSupported: "क्षेत्रीय विविधता और ऐतिहासिक रूपांतरण पर आधुनिक व्याख्या।",
    verificationStatus: "verified",
    reliabilityNote: "Major scholarly synthesis; strongest for the early-modern to modern periods.",
    citation: "Bayly, Susan. Caste, Society and Politics in India from the Eighteenth Century to the Modern Age. Cambridge University Press, 1999. doi:10.1017/CHOL9780521264341.",
  },
  {
    key: "dirks",
    title: "Castes of Mind: Colonialism and the Making of Modern India",
    organization: "Princeton University Press",
    url: "https://press.princeton.edu/books/paperback/9780691088952/castes-of-mind",
    domain: "press.princeton.edu",
    snippet: "Nicholas B. Dirks on colonial knowledge, ethnography, census, and the modern consolidation of caste as an all-India category.",
    extractedText: "Dirks does not argue that the British created every caste relation from nothing. He argues that colonial knowledge and administration transformed caste into a dominant, standardised language for describing and governing India's diverse social identities.",
    publishedAt: "2001",
    retrievedAt: "2026-08-13",
    tier: 3,
    score: 94,
    used: true,
    language: "en",
    relevanceScore: 95,
    authorityScore: 96,
    primarySource: false,
    academicSource: true,
    reasonForInclusion: "औपनिवेशिक ज्ञान और जनगणना पर प्रभावशाली विद्वत् व्याख्या।",
    author: "Nicholas B. Dirks",
    year: "2001",
    publisher: "Princeton University Press",
    sourceType: "scholarly",
    identifier: "ISBN-9780691088952",
    relevantChapter: "10, 12",
    claimSupported: "औपनिवेशिक वर्गीकरण ने जाति को कैसे पुनर्गठित किया।",
    verificationStatus: "verified",
    reliabilityNote: "Scholarly interpretation; it does not erase precolonial hierarchy.",
    citation: "Dirks, Nicholas B. Castes of Mind: Colonialism and the Making of Modern India. Princeton University Press, 2001.",
  },
  {
    key: "annotated",
    title: "Beef, Brahmins, and Broken Men: An Annotated Critical Selection from The Untouchables",
    organization: "Columbia University Press",
    url: "https://cup.columbia.edu/book/beef-brahmins-and-broken-men/9780231195843/",
    domain: "cup.columbia.edu",
    snippet: "Annotated critical selection edited by Alex George and S. Anand, with an introduction by Kancha Ilaiah Shepherd.",
    extractedText: "The Columbia University Press edition describes Ambedkar's history as deductive and at times speculative. Its annotations place his textual use, departures, insights, and slippages into conversation with later scholarship, making it especially useful for critical rather than devotional reading.",
    publishedAt: "2020-04-07",
    retrievedAt: "2026-08-13",
    tier: 3,
    score: 96,
    used: true,
    language: "en",
    relevanceScore: 100,
    authorityScore: 97,
    primarySource: false,
    academicSource: true,
    reasonForInclusion: "आंबेडकर के 1948 तर्क का स्रोत-जाँच सहित आलोचनात्मक संस्करण।",
    author: "B. R. Ambedkar; edited and annotated by Alex George and S. Anand",
    year: "2020",
    publisher: "Columbia University Press",
    sourceType: "scholarly",
    identifier: "DOI-10.7312/ambe19584",
    relevantChapter: "3, 6, 7, 10–11, 14",
    claimSupported: "आंबेडकर की पद्धति की शक्ति, अनुमानात्मकता और आधुनिक आलोचनात्मक पाठ।",
    verificationStatus: "verified",
    reliabilityNote: "Scholarly annotated edition; distinguishes original argument from later commentary.",
    citation: "Ambedkar, B. R. Beef, Brahmins, and Broken Men, ed. Alex George and S. Anand. Columbia University Press, 2020. doi:10.7312/ambe19584.",
  },
  {
    key: "dnjha",
    title: "The Myth of the Holy Cow",
    organization: "Verso Books",
    url: "https://www.versobooks.com/products/1789-the-myth-of-the-holy-cow",
    domain: "versobooks.com",
    snippet: "D. N. Jha's documented study of cattle sacrifice, meat, and changing attitudes to the cow in Indian textual traditions.",
    extractedText: "D. N. Jha argues from Hindu, Buddhist, and Jain textual materials that cattle sacrifice and beef consumption occurred in parts of ancient India and that attitudes changed over time. This evidence challenges a timeless universal taboo, but it does not by itself prove Ambedkar's complete causal explanation of untouchability.",
    publishedAt: "2002",
    retrievedAt: "2026-08-13",
    tier: 3,
    score: 93,
    used: true,
    language: "en",
    relevanceScore: 97,
    authorityScore: 93,
    primarySource: false,
    academicSource: true,
    reasonForInclusion: "प्राचीन आहार और गाय की पवित्रता के इतिहास पर विद्वत् अध्ययन।",
    author: "D. N. Jha",
    year: "2002",
    publisher: "Verso",
    sourceType: "scholarly",
    identifier: "ISBN-9781859846766",
    relevantChapter: "6, 10–11",
    claimSupported: "प्राचीन आहार की विविधता; पूर्ण कारण-श्रृंखला नहीं।",
    verificationStatus: "verified",
    reliabilityNote: "Scholarly historical argument based mainly on textual evidence.",
    citation: "Jha, D. N. The Myth of the Holy Cow. Verso, 2002.",
  },
  {
    key: "rao",
    title: "The Caste Question: Dalits and the Politics of Modern India",
    organization: "University of California Press",
    url: "https://www.ucpress.edu/books/the-caste-question/paper",
    domain: "ucpress.edu",
    snippet: "Anupama Rao's historical anthropology of Dalit political subjecthood, civil rights, law, property, and violence.",
    extractedText: "Rao studies how stigmatised subjects became rights-bearing political actors in colonial and postcolonial western India. The work links caste to property, gender, violence, law, and Dalit mobilisation rather than treating caste only as ritual belief.",
    publishedAt: "2009",
    retrievedAt: "2026-08-13",
    tier: 3,
    score: 92,
    used: true,
    language: "en",
    relevanceScore: 94,
    authorityScore: 96,
    primarySource: false,
    academicSource: true,
    reasonForInclusion: "आधुनिक दलित राजनीति और अधिकारों का अभिलेख-आधारित अध्ययन।",
    author: "Anupama Rao",
    year: "2009",
    publisher: "University of California Press",
    sourceType: "scholarly",
    identifier: "ISBN-9780520257610",
    relevantChapter: "8, 10, 13–14",
    claimSupported: "सामाजिक बहिष्कार से नागरिक अधिकार तक के आधुनिक राजनीतिक रूपांतरण।",
    verificationStatus: "verified",
    reliabilityNote: "Scholarly monograph focused on colonial and postcolonial western India.",
    citation: "Rao, Anupama. The Caste Question: Dalits and the Politics of Modern India. University of California Press, 2009.",
  },
];

export function augmentAchhootSources(
  existing: SourceRecord[],
  allocateId?: () => number
): SourceRecord[] {
  const out = [...existing];
  const max = () => out.reduce((n, source) => Math.max(n, Number(source.id) || 0), 0);
  for (const template of ACHHOOT_SOURCE_TEMPLATES) {
    const found = out.find(
      (source) => source.url === template.url || source.identifier === template.identifier || source.title === template.title
    );
    const { key: _key, ...source } = template;
    if (found) {
      const id = found.id;
      const chapterIds = found.chapterIds;
      Object.assign(found, source, { id, chapterIds });
      continue;
    }
    out.push({ ...source, id: allocateId ? allocateId() : max() + 1 });
  }
  return out;
}

export function achhootSourceMap(sources: SourceRecord[]): Record<AchhootSourceKey, number | undefined> {
  const result = {} as Record<AchhootSourceKey, number | undefined>;
  for (const template of ACHHOOT_SOURCE_TEMPLATES) {
    const found = sources.find(
      (source) => source.url === template.url || source.identifier === template.identifier || source.title === template.title
    );
    result[template.key] = found?.id;
  }
  return result;
}
